name: Deploy App

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ vars.APP_NAME }}:latest
  SSH: ${{vars.SSH_USER}}@${{vars.SSH_HOST}}

jobs:
  update-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ vars.APP_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ vars.APP_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known hosts
        run: |
          ssh-keyscan -H ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image from GHCR
        run: docker pull $IMAGE_NAME

      - name: Deploy to remote server
        run: |
          echo "Deploying to $SSH"
          echo "Checking running containers..."
          echo 'docker ps -a'
          ssh $SSH 'docker stop ${{vars.APP_NAME}} && docker rm ${{vars.APP_NAME}}  || true'
          echo "Checking network..."
          ssh $SSH 'docker network inspect ${{vars.APP_NETWORK}} >/dev/null 2>&1 || docker network create ${{vars.APP_NETWORK}}'
          echo "Starting container..."
          ssh $SSH 'cd ${{vars.WORK_DIR}} && docker run -d --name ${{vars.APP_NAME}} --network ${{vars.APP_NETWORK}}  -p ${{vars.APP_PORT}}:80 ghcr.io/${{ github.repository_owner }}/${{ vars.APP_NAME }}:latest'
